### ISSUE TITLE
State of project

### ISSUE THREAD

**Issue by buggymcbugfix** [Lysxia/unparse-attoparsec#3]
I was wondering what the state of the project is.

Is it usable in a semi-serious way and will it likely be maintained?

Thanks!

**Comment by Lysxia** [comment]
Hi,

> Is it usable in a semi-serious way 

That's exactly right. I have some small examples working, but just haven't gotten around to use it in any bigger projects or to do serious testing on it.

> and will it likely be maintained?

Yes, I'll happily discuss feature requests and review patches.

**Comment by Lysxia** [comment]
I will do a bit of clean up to make this compatible with recent base versions before making a release.

**Comment by buggymcbugfix** [comment]
Great, thanks for that information.

**Comment by Lysxia** [comment]
It's out https://hackage.haskell.org/package/unparse-attoparsec !
